import React from "react";


export const ResourceData = [
    {
        title: "Grade 9",
        subNav: [{grade: "Grade 9", title: "Amharic",resource:["http://elearn.moe.gov.et/resource-view/4389/4","http://elearn.moe.gov.et/resource-view/4393/4","http://elearn.moe.gov.et/resource-view/4398/4"] }, {grade: "Grade 9", title: "English",resource:["http://elearn.moe.gov.et/resource-view/4288/4","http://elearn.moe.gov.et/resource-view/4285/4"] }, {grade: "Grade 9", title: "Afaan Oromo",resource:[] }, {grade: "Grade 9", title: "Biology",resource:["http://elearn.moe.gov.et/resource-view/1260/4","http://elearn.moe.gov.et/resource-view/1262/4","http://elearn.moe.gov.et/resource-view/1289/4"] }, {grade: "Grade 9", title: "Chemisry",resource:["http://elearn.moe.gov.et/resource-view/1564/4","http://elearn.moe.gov.et/resource-view/1515/4"] }, {grade: "Grade 9", title: "Physics",resource:["http://elearn.moe.gov.et/resource-view/1809/4","http://elearn.moe.gov.et/resource-view/1817/4","http://elearn.moe.gov.et/resource-view/1817/4"] }, {grade: "Grade 9", title: "Math",resource:["http://elearn.moe.gov.et/resource-view/3538/4","http://elearn.moe.gov.et/resource-view/3566/4"] }, {grade: "Grade 9", title: "Citizenship",resource:["http://elearn.moe.gov.et/resource-view/4412/4","http://elearn.moe.gov.et/resource-view/4603/4"] }, { grade: "Grade 9",title: "History",resource:[] }, { title: "ICT",resource:[] }, ]
    },
    {
        title: "Grade 10",
        subNav: [{grade: "Grade 10", title: "Amharic",resource:["http://elearn.moe.gov.et/resource-view/4358/4","http://elearn.moe.gov.et/resource-view/4353/4","http://elearn.moe.gov.et/resource-view/4147/4"] }, {grade: "Grade 10", title: "English",resource:["http://elearn.moe.gov.et/resource-view/4142/4","http://elearn.moe.gov.et/resource-view/4161/4","http://elearn.moe.gov.et/resource-view/4141/4"] }, {grade: "Grade 10", title: "Afaan Oromo",resource:[""] }, {grade: "Grade 10", title: "Biology",resource:["http://elearn.moe.gov.et/resource-view/1371/4","http://elearn.moe.gov.et/resource-view/1384/4","http://elearn.moe.gov.et/resource-view/1379/4"] }, {grade: "Grade 10", title: "Chemisry",resource:["http://elearn.moe.gov.et/resource-view/1650/4","http://elearn.moe.gov.et/resource-view/1602/4"] }, {grade: "Grade 10", title: "Physics",resource:["http://elearn.moe.gov.et/resource-view/1857/4","http://elearn.moe.gov.et/resource-view/1836/4","http://elearn.moe.gov.et/resource-view/1860/4"] }, {grade: "Grade 10", title: "Math",resource:["http://elearn.moe.gov.et/resource-view/3361/4"] }, {grade: "Grade 10", title: "Citizenship",resource:["http://elearn.moe.gov.et/resource-view/4612/4","http://elearn.moe.gov.et/resource-view/4421/4"]}, {grade: "Grade 10", title: "History" }, {grade: "Grade 10", title: "ICT" }, ]
    },
    {
        title: "Grade 11",
        subNav: [{grade: "Grade 11", title: "Amharic",resource:["http://elearn.moe.gov.et/resource-view/4302/4"] }, {grade: "Grade 11", title: "English",resource:["http://elearn.moe.gov.et/resource-view/4259/4","http://elearn.moe.gov.et/resource-view/1154/15","http://elearn.moe.gov.et/resource-view/1155/15","http://elearn.moe.gov.et/resource-view/4181/4"] }, {grade: "Grade 11",  title: "Afaan Oromo",resource:[] }, {grade: "Grade 11",  title: "Biology",resource:["http://elearn.moe.gov.et/resource-view/1122/15","http://elearn.moe.gov.et/resource-view/369/14","http://elearn.moe.gov.et/resource-view/371/14","http://elearn.moe.gov.et/resource-view/1428/4"] }, {grade: "Grade 11",  title: "Chemisry",resource:["http://elearn.moe.gov.et/resource-view/1237/15","http://elearn.moe.gov.et/resource-view/383/15","http://elearn.moe.gov.et/resource-view/1680/4"] }, {grade: "Grade 11",  title: "Physics",resource:["http://elearn.moe.gov.et/resource-view/451/15","http://elearn.moe.gov.et/resource-view/1230/15","http://elearn.moe.gov.et/resource-view/449/15","http://elearn.moe.gov.et/resource-view/448/15"] }, {grade: "Grade 11",  title: "Math",resource:["http://elearn.moe.gov.et/resource-view/3443/4",] }, {grade: "Grade 11",  title: "Citizenship",resource:["http://elearn.moe.gov.et/resource-view/4590/4"] }, {grade: "Grade 11",  title: "History",resource:["http://elearn.moe.gov.et/resource-view/380/14","http://elearn.moe.gov.et/resource-view/384/14","http://elearn.moe.gov.et/resource-view/386/14"] }, {grade: "Grade 11",  title: "ICT",resource:[] }, ]
    },
    {
        title: "Grade 12",
        subNav: [{grade: "Grade 12",  title: "Amharic",resource:["http://elearn.moe.gov.et/resource-view/4326/4",""] }, {grade: "Grade 12", title: "English",resource:["http://elearn.moe.gov.et/resource-view/1162/15",] }, {grade: "Grade 12", title: "Afaan Oromo",resource:[] }, {grade: "Grade 12", title: "Biology",resource:["http://elearn.moe.gov.et/resource-view/1482/4", "http://elearn.moe.gov.et/resource-view/1481/4",""]}, {grade: "Grade 12", title: "Chemisry",resource:["http://elearn.moe.gov.et/resource-view/181/15","http://elearn.moe.gov.et/resource-view/183/15","http://elearn.moe.gov.et/resource-view/389/14"] }, {grade: "Grade 12", title: "Physics",resource:["http://elearn.moe.gov.et/resource-view/1233/15","http://elearn.moe.gov.et/resource-view/1230/15"] }, {grade: "Grade 12", title: "Math",resource:["http://elearn.moe.gov.et/resource-view/3482/4","http://elearn.moe.gov.et/resource-view/226/15","http://elearn.moe.gov.et/resource-view/479/15","http://elearn.moe.gov.et/resource-view/1173/15"] }, {grade: "Grade 12", title: "Citizenship",resource:["http://elearn.moe.gov.et/resource-view/4478/4","http://elearn.moe.gov.et/resource-view/4590/4"] }, {grade: "Grade 12", title: "History",resource:["http://elearn.moe.gov.et/resource-view/380/14","http://elearn.moe.gov.et/resource-view/384/14","http://elearn.moe.gov.et/resource-view/386/14",] }, {grade: "Grade 12",  title: "ICT",resource:[] }, ]
    },
    
]
